id: I6F94CF1D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:54:33+00:00'
last_modified: '2022-06-08T02:36:19.174764+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6161
  title: རྫོགས་ཆེན་ཟབ་ཆོས་ཕྱོགས་བསྒྲིགས་མན་ངག་ནོར་བུའི་གཏེར་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6A0D:
      image_group_id: I1KG8459
      title: ''
      total_pages: 650
      order: 1
      base_file: 6A0D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
